/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f4xx.h>

//Global Variables
uint8_t tim2_flag = 0;
volatile uint8_t exti_flag = 0;
uint8_t counter = 0;

//Function heads
void init_RCC(void);
void init_PORTC(void);
void init_PORTH(void);
void init_TIM2(void);
void init_EXTI(void);
void TIM2_IRQHandler(void);

int main(void)
{
    //Function Call
    init_RCC();
    init_PORTC();
    init_PORTH();
    init_TIM2();

    /* Loop forever */
    while(1){
        if(tim2_flag){
            tim2_flag = 0;
            GPIOH->ODR ^= GPIO_ODR_OD1; //Blinky 500 ms
        }
        if(exti_flag){
            exti_flag = 0;
            counter += 1;
        }
    }
}

void init_RCC(void){
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOCEN;//GPIOC
    RCC->AHB1ENR |= RCC_AHB1ENR_GPIOHEN; //Señal de reloj para H
    RCC->APB1ENR |= RCC_APB1ENR_TIM2EN; //Señal de reloj para TIM2
    RCC->APB2ENR |= RCC_APB2ENR_SYSCFGEN; //Señal de reloj para Sysconfig
}

void init_PORTC(void){
    //Moder 00 Input
    GPIOC->MODER &= ~(GPIO_MODER_MODE1);//Input Mode

    //PUPDR 00
    GPIOC->PUPDR &= ~(GPIO_PUPDR_PUPD1);//No Pull Up No Pull Down
}

void init_PORTH(void){
    //PH1
    //No hay necesidad de limpiarlo porque no tiene una dirección predeterminada
    GPIOH->MODER |= GPIO_MODER_MODE1_0; //Output mode
    //OTYPER en push pull
    GPIOH->OTYPER &= ~(GPIO_OTYPER_OT1);
    //OSPEEDR en medium speed
    GPIOH->OSPEEDR |= GPIO_OSPEEDR_OSPEED1_0;
    //No pull No pull down
    GPIOH->PUPDR &= ~(GPIO_PUPDR_PUPD1);
    //ODR
    GPIOH->ODR |= GPIO_ODR_OD1;
}

void init_TIM2(void){
    //CR1
    TIM2->CR1 &= ~(0b1 << TIM_CR1_DIR_Pos);//Counting upwards
    TIM2->CR1 &= ~(0b1 << TIM_CR1_ARPE_Pos);//Autoreaload not buffered
    //DIER
    TIM2->DIER |= (0b1 << TIM_DIER_UIE_Pos);
    //SR
    TIM2->SR &= ~(0b1 << TIM_SR_UIF_Pos);
    //CNT
    TIM2->CNT = 0;
    //PSC
    TIM2->PSC = 15999;
    //ARR
    TIM2->ARR = 499;
    //Nvic activate
    NVIC_EnableIRQ(TIM2_IRQn);
    //CEN
    TIM2->CR1 |= (0b1 << TIM_CR1_CEN_Pos);
}

void init_EXTI(void){
    //Configuramos canal de EXTI
    SYSCFG->EXTICR[0] &= ~(SYSCFG_EXTICR1_EXTI1);

    //Configuramos el canal 1
    SYSCFG->EXTICR[0] |= (SYSCFG_EXTICR1_EXTI1_PC);

    //Flanco de subida en PC1
    EXTI->RTSR |= EXTI_RTSR_TR1;

    //Nvic EN
    NVIC_EnableIRQ(EXTI1_IRQn);

    //Bajamos la bandera de la interrupción
    EXTI->PR |= EXTI_PR_PR1;

    //Activamos la interrupción
    EXTI->IMR |= EXTI_IMR_IM1;

}

void TIM2_IRQHandler(void){
    if(TIM2->SR && TIM_SR_UIF){
        TIM2->SR &= ~(TIM_SR_UIF);
        tim2_flag = 1;
    }
}

void EXTI1_IRQHandler(void){
    if(EXTI->PR && EXTI_PR_PR1){
        //Limpiamos bandera
        EXTI->PR |= EXTI_PR_PR1;
        exti_flag = 1;
    }
}
